# Generated by Django 2.1 on 2018-11-03 04:50

import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20181103_1250'),
        ('users', '0003_auto_20181103_1250'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodePermission',
            fields=[
                ('org_id', models.CharField(blank=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_expired', models.DateTimeField(default=common.utils.date_expired_default, verbose_name='Date expired')),
                ('created_by', models.CharField(blank=True, max_length=128, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Node', verbose_name='Node')),
                ('system_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.SystemUser', verbose_name='System user')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserGroup', verbose_name='User group')),
            ],
            options={
                'verbose_name': 'Asset permission',
            },
        ),
        migrations.AlterModelOptions(
            name='assetpermission',
            options={'verbose_name': 'Asset permission'},
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='date_start',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date start'),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='nodes',
            field=models.ManyToManyField(blank=True, related_name='granted_by_permissions', to='assets.Node', verbose_name='Nodes'),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='org_id',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='asset_permissions', to='users.UserGroup', verbose_name='User group'),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='asset_permissions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='assetpermission',
            name='date_expired',
            field=models.DateTimeField(db_index=True, default=common.utils.date_expired_default, verbose_name='Date expired'),
        ),
        migrations.AlterField(
            model_name='assetpermission',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.RemoveField(
            model_name='assetpermission',
            name='asset_groups',
        ),
        migrations.AlterUniqueTogether(
            name='assetpermission',
            unique_together={('org_id', 'name')},
        ),
    ]
