# Generated by Django 2.1 on 2018-11-03 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='org_id',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='session',
            name='date_last_active',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date last active'),
        ),
        migrations.AddField(
            model_name='session',
            name='org_id',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='session',
            name='protocol',
            field=models.CharField(choices=[('ssh', 'ssh'), ('rdp', 'rdp')], default='ssh', max_length=8),
        ),
        migrations.AddField(
            model_name='session',
            name='remote_addr',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Remote addr'),
        ),
        migrations.AddField(
            model_name='session',
            name='terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminal.Terminal'),
        ),
        migrations.AddField(
            model_name='status',
            name='terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='terminal.Terminal'),
        ),
        migrations.AddField(
            model_name='task',
            name='terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminal.Terminal'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='command_storage',
            field=models.CharField(default='default', max_length=128, verbose_name='Command storage'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='replay_storage',
            field=models.CharField(default='default', max_length=128, verbose_name='Replay storage'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminal', to=settings.AUTH_USER_MODEL, verbose_name='Application User'),
        ),
        migrations.AlterField(
            model_name='command',
            name='asset',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='command',
            name='system_user',
            field=models.CharField(db_index=True, max_length=64, verbose_name='System user'),
        ),
        migrations.AlterField(
            model_name='command',
            name='user',
            field=models.CharField(db_index=True, max_length=64, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_start',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date start'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Name'),
        ),
    ]
